// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMPp7WEdKzocCUXgIJBGlnG0JFne8fwXc',
    appId: '1:565492441016:web:f093c5950e8863678ef94d',
    messagingSenderId: '565492441016',
    projectId: 'clone-7fffd',
    authDomain: 'clone-7fffd.firebaseapp.com',
    storageBucket: 'clone-7fffd.firebasestorage.app',
    measurementId: 'G-C3TJBBNRV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByVcSy5LZbkVYxfeKpiXRDBowaCaY12oQ',
    appId: '1:565492441016:android:b34fff7f4fd556db8ef94d',
    messagingSenderId: '565492441016',
    projectId: 'clone-7fffd',
    storageBucket: 'clone-7fffd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhBYG2GuvaDtT3h6t-l2ea_U8KsQrAiZ4',
    appId: '1:565492441016:ios:1675533de2ae84c28ef94d',
    messagingSenderId: '565492441016',
    projectId: 'clone-7fffd',
    storageBucket: 'clone-7fffd.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );
}
